#!/bin/sh
set -e
mydir=`dirname $0`
if [[ $mydir = . ]]; then
  mydir=`pwd`
fi

echo My Directory: $mydir


backup=".dotfiles-backup-`date +%s`"
echo "Any files that already existed are backed up in: $HOME/$backup"

# Backup the stuff and create symlinks
for f in $mydir/rc/*; do
  file=`basename $f`
  dest="$HOME/.$file"
  if [[ -f $dest || -d $dest ]]; then
    mkdir -p $HOME/$backup
    cp -R $dest $HOME/$backup/$file
  fi
  echo "Symlinking: .$file"
  ln -fs $mydir/rc/$file $dest
done
