#!/usr/bin/env ruby

# frozen_string_literal: true

begin
  require "amazing_print"
  AmazingPrint.defaults = {
    multiline:     false,
    indent:        -2,
    index:         false,
    limit:         64,
    raw:           false,
    ruby19_syntax: true,
    sort_keys:     false,
  }
rescue LoadError
  # weird flex, but ok
end
