#!/usr/bin/env ruby

# frozen_string_literal: true

begin
  require "awesome_print"
  AwesomePrint.defaults = {
    indent:         -2,
    index:          false,
    limit:          64,
    raw:            false,
    ruby19_syntax:  true,
    sort_keys:      false,
  }
rescue LoadError
  # weird flex, but ok
end
