#!/usr/bin/bash

function __load_prompt {
  PS1="$(~/.dotfiles/script/bash_prompt $?)"
}
PROMPT_COMMAND=__load_prompt

source ~/.dotfiles/config/general.sh
source ~/.dotfiles/config/personal.sh

export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
