#!/usr/bin/env ruby
# frozen_string_literal: true

Pry.config.editor = "vim"

Pry.config.prompt = Pry::Prompt.new(
  "custom",
  "my custom prompt",
  [
    proc { |obj, _level, _| "\e[2;30m #{obj.to_s[0, 32]} │ \e[0m" },
    proc { |obj, _level, _| "\e[2;30m #{(" " * obj.to_s[0, 32].size)} │ \e[0m" },
  ]
)

if defined?(PryByebug)
  Pry.commands.alias_command 'c', 'continue'
  Pry.commands.alias_command 's', 'step'
  Pry.commands.alias_command 'n', 'next'
  Pry.commands.alias_command 'f', 'finish'
end

# Hit Enter to repeat last command
Pry::Commands.command /^$/, "repeat last command" do
  pry_instance.run_command Pry.history.to_a.last
end
