let mapleader = ","
" Defer to dedicated plugins which provide more than polyglot's bundled syntax
let g:polyglot_disabled = ['ruby', 'slim', 'rbs', 'cucumber']

if !has('nvim') && filereadable(expand('~/.config/vim/_nvim-defaults.vim'))
  source ~/.config/vim/_nvim-defaults.vim
endif

source ~/.config/vim/_plug.vim

for s:file in glob('~/.config/vim/[^_]*.vim', 0, 1)
  execute 'source' s:file
endfor

if has('gui_macvim')
  source ~/.config/vim/_macvim.vim
endif
