export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.dotfiles/bin:$PATH"

export EDITOR='vim'
export GIT_EDITOR=$EDITOR
export SVN_EDITOR=$EDITOR

export VISUAL='mvim'
export BUNDLER_EDITOR=$VISUAL
export GEMEDITOR=$VISUAL

export JAVA_HOME="/Library/Java/Home"
