# https://starship.rs/
if command -v starship > /dev/null; then
  eval "$(starship init zsh)"
fi

# https://github.com/eza-community/eza
if command -v eza > /dev/null; then
  alias ls='eza --group-directories-first'
  alias l='eza --long --group-directories-first --git --all --time-style=iso'
else
  alias l='ls -FhAlo'
fi

# https://github.com/ajeetdsouza/zoxide
if command -v zoxide > /dev/null; then
  eval "$(zoxide init zsh)"
fi

# https://direnv.net/
if command -v direnv > /dev/null; then
  eval "$(direnv hook zsh)"
fi

# https://asdf-vm.com/
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
fpath=(${ASDF_DATA_DIR:-$HOME/.asdf}/completions $fpath) # append completions to fpath
autoload -Uz compinit && compinit # initialise completions with ZSH's compinit

# Aliases
alias m='mvim'
alias st='git status'
