export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export SHELL=$(which zsh)
PROJECT_PARENT_DIRS=()
source ~/.dotfiles/zsh/rc

if [[ -d "$HOME/.rvm/bin" ]]; then
  export PATH=$PATH:$HOME/.rvm/bin
fi

if [[ -d "/usr/local/sbin" ]]; then
  export PATH=$PATH:/usr/local/sbin
fi
