if [[ -a /usr/local/share/antigen/antigen.zsh ]]; then

  source /usr/local/share/antigen/antigen.zsh

  antigen use oh-my-zsh

  antigen bundle gitfast
  antigen bundle heroku
  antigen bundle aws
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh
  # too slow when pasting commands into terminal
  # antigen bundle https://github.com/zsh-users/zsh-autosuggestions.git
  # bindkey '^ ' autosuggest-accept
  antigen bundle themes

  antigen theme https://gist.github.com/88fa1befc0973f4acf4baf1bc9b511a0.git minimaliain

  antigen apply

  PROMPT=" $PROMPT"

else

  echo "\e[0;31mError: Missing antigen. To install: \e[0;34mbrew install antigen\e[0;00m"

  PROMPT="$ "

fi

source ~/.dotfiles/config/general.sh
source ~/.dotfiles/config/tab_title.zsh
source ~/.dotfiles/config/personal.sh

export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# TODO investigate how to make work
# iterm2_print_user_vars() {
#   iterm2_set_user_var gitBranch $(git name-rev --name-only $(git rev-parse HEAD))
# }

true
