add_newline = false
format = """
$jobs\
$username\
$hostname\
$shlvl\
$directory\
$shell\
${custom.git}\
$cmd_duration\
$status\
$character"""

[jobs]
symbol = " "
style = "dimmed purple"

[directory]
style = "blue"
read_only = " "

[status]
disabled = false
style = "red"
symbol = "✖ "

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[custom.git]
command = "~/.dotfiles/bin/git-prompt"
when = "true"
