# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
${custom.bottom}\
$aws\
$jobs\
$username\
$hostname\
$shlvl\
${custom.git}\
$directory\
$shell\
$cmd_duration\
$status\
$character"""

[jobs]
symbol = " "
style = "dimmed purple"

[directory]
style = "blue"
read_only = " "

[aws]
symbol = " "
format = '[$symbol($profile)(:$region) ]($style)'
style = "yellow"
# [aws.region_aliases]
# ap-southeast-2 = "au"
# us-east-1 = "va"
# us-east-2 = "va"
# [aws.profile_aliases]
# CompanyGroupFrobozzOnCallAccess = 'Frobozz'
# identity = 'id'
# production = 'prod'
# staging = 'stg'

[status]
disabled = false
style = "red"
symbol = "✖ "

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[custom.git]
command = "~/.dotfiles/bin/git-prompt"
when = "true"

[ruby]
symbol = ' '
format = '[$symbol($version )]($style)'
style = 'red'

[custom.bottom]
command = "tput cup 9999 0"
when = "true"
