add_newline = false
format = """
$username\
$hostname\
$shlvl\
$directory\
${custom.tim}\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$env_var\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[directory]
style = "blue"
read_only = " "

[status]
disabled = false
style = "red"
symbol = "✖ "

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[git_branch]
# symbol = " "
symbol = ""
style = "green"
format = "[$symbol$branch]($style) "
truncation_length = 24

[git_status]
format = '([$all_status](yellow)[$ahead_behind]($style) )'
style = "purple"
deleted = " "
modified = " "
staged = " "
stashed = " $count "
untracked = "ﱐ "
ahead = "↑"
behind = "↓"
diverged = "↕"
conflicted = "[ﲅ ](red)"

[custom.tim]
disabled = false
command = "~/.dotfiles/bin/git-time-since-last-commit"
style = "black dimmed"
when = "true"
files = [".git"]
