#!/usr/bin/env ruby

require "fileutils"

def symlink(from, to)
  # print "Installing #{from} to #{to}... "
  from = File.expand_path("../#{from}", __dir__)
  to = File.expand_path(to)
  FileUtils.mkdir_p(File.dirname(to))
  if File.exist?(to)
    if File.directory?(from) || File.directory?(to)
      puts "Skipping #{to}, because I don't want to compare whole directories"
    elsif FileUtils.identical?(from, to)
      puts "Skipping #{to}, files are identical"
    else
      backup = "#{to}.bak"
      puts "Making backup of #{to} in #{backup}"
      FileUtils.copy_file(to, backup)
      FileUtils.ln_sf(from, to, verbose: true)
    end
  else
    FileUtils.ln_s(from, to, verbose: true)
  end
end

Dir["rc/*"].each do |f|
  symlink f, "~/.#{File.basename(f)}"
end

symlink "config/init.vim", "~/.config/nvim/init.vim"

symlink "config/starship.toml", "~/.config/starship.toml"

symlink "config/config.fish", "~/.config/fish/config.fish"

symlink "config/fish/functions", "~/.config/fish/functions"

symlink "config/auto_dark_mode.py", "/Users/iain/Library/ApplicationSupport/iTerm2/Scripts/AutoLaunch/auto_dark_mode.py"
