#!/usr/bin/env bash

pattern='[0-9]{2}_.*'

for file in ~/.dotfiles/shared/*.zsh; do
  if [[ "${file}" =~ $pattern ]]; then
    source $file
  fi
done

for file in ~/.dotfiles/bash/*.sh; do
  if [[ "${file}" =~ $pattern ]]; then
    source $file
  fi
done
